apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push-docker
spec:
  params:
    - name: organization
      type: string
      description: The organization for the Docker image
    - name: repository
      type: string
      description: The repository for the Docker image
    - name: tag
      type: string
      description: The tag for the Docker image
      default: latest
  resources:
    inputs:
      - name: repo
        type: git
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v0.19.0
      env:
        - name: DOCKER_CONFIG
          value: /tekton/home/.docker
      command:
        - /kaniko/executor
        - --dockerfile=Dockerfile
        - --context=/workspace/repo/src
        - --destination=jenkinsxdemo/tekton-gitops-example:$(params.tag)
