apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-build-push
spec:
  params:
    - name: commitHash
      type: string
      description: The directory containing the build context.
  resources:
    - name: repo
      type: git

  tasks:
    # Run linter
    - name: lint
      taskRef:
        name: lint
      resources:
        inputs:
          - name: repo
            resource: repo

    # Run application tests
    - name: test
      taskRef:
        name: test
      resources:
        inputs:
          - name: repo
            resource: repo

    # Build docker image and push to registry
    - name: build-and-push
      taskRef:
        name: build-and-push
      runAfter:
        - test
        - lint
      resources:
        inputs:
          - name: repo
            resource: repo

    # Build docker image and push to registry
    - name: deploy
      taskRef:
        name: deploy
      runAfter:
        - build-and-push
      resources:
        inputs:
          - name: repo
            resource: repo
      params:
        - name: commitHash
          type: string
          description: The directory containing the build context.

    - name: pull-request
      taskRef:
        name: pull-request
      runAfter:
        - build-and-push
      resources:
        inputs:
          - name: repo
            resource: repo
      params:
        - name: commitHash
          type: string
          description: The directory containing the build context.
