apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: deploy-from-source-pipeline-
spec:
  pipelineRef:
    name: deploy-from-source-pipeline
  params:
    - name: imageUrl
      value: https://index.docker.io/v1/jenkinsxdemo/tekton-gitops-example
  serviceAccountName: build-bot
  workspaces:
    - name: git-source
      persistentVolumeClaim:
        claimName: tekton-gitops-example-source-pvc