replicaCount: 1

image:
  repository: jenkinsxdemo/tekton-gitops-example
  tag: latest
  pullPolicy: Always

service:
  name: tekton-gitops-example
  type: NodePort
  externalPort: 3000
  internalPort: 3000

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi


