kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-triggers-role
rules:
  - apiGroups: [ "tekton.dev" ]
    resources: [ "eventlisteners", "triggerbindings", "triggertemplates", "pipelineresources" ]
    verbs: [ "get" ]
  - apiGroups: [ "tekton.dev" ]
    resources: [ "pipelineruns", "pipelineresources" ]
    verbs: [ "create" ]
  - apiGroups: [ "" ]
    resources: [ "services" ]
    verbs: [ "get", "create", "update", "patch" ]
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "get", "create", "update", "patch" ]