apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: tekton-gitops-example-pipelinebinding
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: namespace
      value: tekton-gitops-example
    - name: gitrepositoryurl
      value: $(body.repository.url)
    - name: gitrepositoryname
      value: $(body.repository.name)